# Generated by Django 5.0.4 on 2024-06-12 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blogrecord_alter_products_date_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="count_views",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blogrecord",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_ver",
                    models.FloatField(
                        blank=True,
                        help_text="Укажите номер версии",
                        null=True,
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "name_ver",
                    models.CharField(
                        help_text="Укажите название версии",
                        max_length=100,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.products",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ("number_ver", "name_ver", "is_active", "product"),
            },
        ),
    ]
