# Generated by Django 4.2.2 on 2024-11-19 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_alter_products_options_products_status_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status_public',
        ),
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='products',
            name='publication_status',
            field=models.BooleanField(default=False),
        ),
    ]
